---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openunison-operator-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - openunison.tremolo.io
  - ""
  - apps
  - rbac.authorization.k8s.io
  - extensions
  - apps.openshift.io
  - build.openshift.io
  - image.openshift.io
  - route.openshift.io
  - user.openshift.io
  - batch
  - networking.k8s.io
  resources:
  - routes/custom-host
  - imagestreamimports
  - users
  - groups
  - routes
  - images
  - imagestreams
  - builds
  - buildconfigs
  - deploymentconfigs
  - openunisons
  - openunisons/status
  - pods
  - deployments
  - secrets
  - configmaps
  - services
  - serviceaccounts
  - roles
  - rolebindings
  - ingresses
  - cronjobs
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openunison-operator-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openunison-operator-role
subjects:
- kind: ServiceAccount
  name: openunison-operator
  namespace: {{ .Release.Namespace }}

