---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vcluster-onboard-create-obj-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vcluster-onboard-create-obj-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: vcluster-onboard-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}