{{ if .Values.network_policies.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
{{ if .Values.network_policies.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      application: openunison-{{ .Release.Name }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels: {{ range $key,$value := .Values.network_policies.ingress.labels }}
            {{ $key }}: {{ $value }}
        {{ end }}
  policyTypes:
  - Ingress
{{ end }}
{{ if .Values.network_policies.monitoring.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-prometheus
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      application: openunison-{{ .Release.Name }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels: {{ range $key,$value :=  .Values.network_policies.monitoring.labels }}
            {{ $key }}: {{ $value }}
        {{ end }}
  policyTypes:
  - Ingress
{{ end }}
{{ if .Values.network_policies.apiserver.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      application: openunison-{{ .Release.Name }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels: {{ range $key,$value :=  .Values.network_policies.apiserver.labels }}
            {{ $key }}: {{ $value }}
        {{ end }}
  policyTypes:
  - Ingress
{{ end }}
{{ end }}