---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vcluster-onboard-openunison-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - openunison.tremolo.io
  resources:
  - openunisons
  verbs:
  - 'get'