network:
  openunison_host: "k8sou.apps.domain.int"
  dashboard_host: "k8sdb.apps.domain.int"
  api_server_host: "k8sapi.apps.domain.int"
  session_inactivity_timeout_seconds: 900
  k8s_url: https://k8s-installer-master.tremolo.lan:6443

cert_template:
  ou: "Kubernetes"
  o: "MyOrg"
  l: "My Cluster"
  st: "State of Cluster"
  c: "MyCountry"

image: "docker.io/tremolosecurity/openunison-k8s-login-github:latest"
myvd_config_path: "WEB-INF/myvd.conf"
k8s_cluster_name: kubernetes
enable_impersonation: false

dashboard:
  namespace: "kubernetes-dashboard"
  cert_name: "kubernetes-dashboard-certs"
  label: "k8s-app=kubernetes-dashboard"
  service_name: kubernetes-dashboard
certs:
  use_k8s_cm: false

trusted_certs: []

monitoring:
  prometheus_service_account: system:serviceaccount:monitoring:prometheus-k8s

github:
  client_id: sdfsdfsfsdfsdf
  teams: MyOrg/
       