{{ if not .Values.enable_provisioning }}
---
apiVersion: openunison.tremolo.io/v1
kind: Org
metadata:
  name: local-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: openunison-orgs
    app.kubernetes.io/part-of: openunison
spec:
  label: "#[K8S_DEPLOYMENT_NAME:Local Deployment]"
  azRules:
  {{ $length := len .Values.openunison.az_groups }}
  {{ if eq $length 0 }}
  - scope: dn
    constraint: o=Tremolo
  {{ else }}
  {{ range $az_group := .Values.openunison.az_groups }}
  - scope: filter
    constraint: (groups={{ $az_group }})
  {{ end }}
  {{ end }}
  description: "#[K8S_DEPLOYMENT_DESC:Current Cluster]"
  parent: B158BD40-0C1B-11E3-8FFD-0800200C9A66
  showInPortal: true
  showInReports: false
  showInRequestAccess: false
  uuid: b1bf4c92-7220-4ad2-91af-ee0fe0af7312
{{ end }}