---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openunison-{{ .Release.Name }}
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: network
  name: openunison-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  {{ if eq .Values.network.ingress_type "istio" }}
  - name: https-{{ .Release.Name }}
  {{ else }}
  - name: openunison-secure-{{ .Release.Name }}
  {{ end }}
    port: 443
    protocol: TCP
    targetPort: 8443
  {{ if eq .Values.network.ingress_type "istio" }}
  - name: http-{{ .Release.Name }}
  {{ else }}
  - name: openunison-insecure-{{ .Release.Name }}
  {{ end }}
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    application: openunison-{{ .Release.Name }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
status:
  loadBalancer: {}
