{{ if and .Values.cluster.management.enabled .Values.cluster.management.viewers.enabled }}
---
apiVersion: openunison.tremolo.io/v1
kind: Org
metadata:
  name: {{ .Values.cluster.name }}-namespace-viewers
  namespace: {{ .Release.Namespace }}
spec:
  label: Viewers
  azRules:
  - constraint: {{ .Values.cluster.management.viewers.az.constraint }}
    scope: {{ .Values.cluster.management.viewers.az.scope }}
  description: Namespace Viewer
  parent: org-cluster-{{ .Values.cluster.name }}
  showInPortal: false
  showInReports: false
  showInRequestAccess: true
  uuid: org-cluster-{{ .Values.cluster.name }}-viewers
{{ end }}