{{ if and .Values.cluster.management.enabled .Values.cluster.management.viewers.enabled }}
---
apiVersion: openunison.tremolo.io/v1
kind: Workflow
metadata:
  name: {{ .Values.cluster.name }}-namespace-viewer
  namespace: {{ .Release.Namespace }}
spec:
  description: ClusterRole view for the $name$ namespace
  inList: true
  label: $name$ Viewer
  orgId: org-cluster-{{ .Values.cluster.name }}-viewers
  dynamicConfiguration:
    dynamic: true
    className: com.tremolosecurity.unison.openshiftv3.wf.OpenShiftWorkflows
    params:
    - name: target
      value: k8s-{{ .Values.cluster.name }}
    - name: kind
      value: /api/v1/namespaces
    - name: filter
      value: default
    - name: filter
      value: kube-system
    - name: filter
      value: kube-public
  tasks: |-
           - taskType: addAttribute
             name: cluster
             value: k8s-{{ .Values.cluster.name }}
             remove: false
             addToRequest: true
           - taskType: callWorkflow
             name: k8s-namespace-viewer
{{ end }}
