# If set to true the CRDs will be deployed.  Otherwise the CRs are ignored.
crd:
  deploy: true
  betas: false
  webhooks: true

services:
  node_selectors: []
  pullSecret: ""

image: docker.io/tremolosecurity/betas:operator-v1024
  