primaryCluster:
  name: Control Plane Cluster
  description: Central control plane cluster used to manage other clusters

openunison:
  orchestra_release_name: orchestra
  orchestra_login_portal_name: orchestra-login-portal
  naas:
    forms:
      new_namespace:
        use_default: true
    workflows:
      new_namespace:
        use_default: true
    groups:
      roles: []
      default:
      - name: administrators
        rolebindingtype: ClusterRole
        rolebinding: admin
        bindingname: admins
        description: Manage kubernetes namespace $cluster$ $nameSpace$
        external:
          fieldName: adminGroup
          label: "Administrator Group"
          errorMessage: "Invalid administrator group"
      - name: viewer
        rolebindingtype: ClusterRole
        rolebinding: view
        description: View kubernetes namespace $cluster$ $nameSpace$
        bindingname: viewers
        external:
          fieldName: viewerGroup
          label: "Viewer Group"
          errorMessage: "Invalid viewer group"
      internal:
        enabled: true
        suffix: "-internal"
      external:
        suffix: "-external"
        enabled: false
        admin_group: "CN=openunison-admins,CN=Users,DC=ent2k12,DC=domain,DC=com"
        cluster_admin_group: "CN=k8s_login_ckuster_admins,CN=Users,DC=ent2k12,DC=domain,DC=com"