primaryCluster:
  name: Control Plane Cluster
  description: Central control plane cluster used to manage other clusters

openunison:
  orchestra_release_name: orchestra
  orchestra_login_portal_name: orchestra-login-portal
  naas:
    forms:
      new_namespace:
        use_default: true
    workflows:
      new_namespace:
        use_default: true
    groups:
      roles: []
      default:
      - name: administrators
        rolebindingtype: ClusterRole
        rolebinding: admin
        bindingname: admins
        description: Manage kubernetes namespace $cluster$ $nameSpace$
        workflow:
          label: "namespace administrator"
          displayLabel: $name$ Administrator
          emailTemplate: Approve administrator access to $cluster$ $name$
          approvalLabel: Approve administrator access for $cluster$ - $name$
          userNotification:
            subject: Admin access to $cluster$ $name$ approved
            message: Your access has been approved
          org:
            label: Administrators
            description: Namespace Administrators
        external:
          fieldName: adminGroup
          label: "Administrator Group"
          errorMessage: "Invalid administrator group"
      - name: viewer
        rolebindingtype: ClusterRole
        rolebinding: view
        description: View kubernetes namespace $cluster$ $nameSpace$
        bindingname: viewers
        external:
          fieldName: viewerGroup
          label: "Viewer Group"
          errorMessage: "Invalid viewer group"
        workflow:
          label: "namespace viewer"
          displayLabel: $name$ Administrator
          emailTemplate: Approve viewer access to $cluster$ $name$
          approvalLabel: Approve viewer access for $cluster$ - $name$
          userNotification:
            subject: View access to $cluster$ $name$ approved
            message: Your access has been approved
          org:
            label: Viewers
            description: Namespace Viewers
      internal:
        enabled: true
        suffix: "-internal"
      external:
        suffix: "-external"
        enabled: false
        admin_group: "CN=openunison-admins,CN=Users,DC=ent2k12,DC=domain,DC=com"
        cluster_admin_group: "CN=k8s_login_ckuster_admins,CN=Users,DC=ent2k12,DC=domain,DC=com"