---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vcluster-onboard-crds-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vcluster-onboard-crds-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: vcluster-onboard-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}